config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :projects
  # get "admin/index"
  # get "up" => "rails/health#show", as: :rails_health_check
  #
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "admin#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project, optional: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @message = "Hello, task manager"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  def index
    @projects = Project.all
  end

  def show

  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_path, status: :see_other, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def set_project
    @project = Project.includes(:tasks).find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, :status, :due_date)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  def index
    @tasks = Task.all
    @task = Task.new
  end

  def show
  end

  def edit
    @task = Task.find_by_id(params[:id])
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_back_or_to tasks_path, notice: "Task was successfully created."
    else
      redirect_back_or_to tasks_path, alert: "The task could not be created."
    end
  end

  def update
    if @task.update(task_params)
      redirect_back_or_to tasks_path, notice: "Task was successfully updated."
    else
      redirect_back_or_to tasks_path, alert: "The task could not be updated."
    end
  end

  def destroy
    @task.destroy!
    redirect_back_or_to tasks_path, notice: "Task was successfully destroyed."
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:title, :description, :status, :due_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Task Manager" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/favicon.ico" type="image/png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body class="base-layout">
    <div class="header">
      <div class="logo">
        Task Manager
      </div>
    </div>
    <div class="content">
      <div class="tabs">
        <%= link_to "Tasks", tasks_path, class: "tab", id: "tasks-tab" %>
        <%= link_to "Projects", projects_path, class: "tab", id: "projects-tab" %>
      </div>

      <div class="tab-content">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

<script type="module">
    $(document).on("turbo:load", function () {
        const tasksTab = document.getElementById("tasks-tab");
        const projectsTab = document.getElementById("projects-tab");

        if (window.location.pathname.includes("projects")) {
            projectsTab.classList.add("active");
        } else {
            tasksTab.classList.add("active");
        }
    })
</script>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.number_field :status %>
  </div>

  <div>
    <%= form.label :due_date, style: "display: block" %>
    <%= form.datetime_field :due_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Title:</strong>
    <%= project.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= project.status %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= project.due_date %>
  </p>

  <p>
    <strong> Project Tasks </strong>
    <% project.tasks.each do |task| %>
      <%= render task %>
    <% end %>
  </p>

</div>

app/views/projects/edit.html.erb
<% content_for :title, "Editing project" %>

<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Projects" %>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<% content_for :title, "New project" %>

<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.number_field :status %>
  </div>

  <div>
    <%= form.label :due_date, style: "display: block" %>
    <%= form.datetime_field :due_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_new.haml
.task-container.new-task{onclick: 'showForm();'}
  %span#create-task-text
    + Create task
  = form_with model: @task, class: 'task-form hidden', id: 'task-form' do |f|
    = f.text_field :title, placeholder: 'Enter task title', onfocus: 'highlightInput()'
    = f.date_field :due_date, class: 'task-due-date'
    %div.action-buttons.hidden
      %button.check{type: 'button', onclick: 'this.form.submit();'} ✓
      %button.cancel{type: 'button', onclick: 'clearInput()'} ✗

:javascript
  function showForm() {
    document.getElementById('task-form').classList.remove('hidden');
    document.getElementById('create-task-text').classList.add('hidden');
  }

  function highlightInput() {
    document.getElementById('task-form').classList.add('show-buttons');
  }

  function clearInput() {
    document.getElementById('task-form').classList.add('hidden');
    document.getElementById('task-form').classList.remove('show-buttons');
  }

app/views/tasks/_task.haml
.task-container{id: "task-#{task.id}"}
  = link_to task.title, edit_task_path(task.id), class: 'title edit-link'
  %span.due-date
    %strong
      Due Date:
    = task.due_date ? task.due_date.strftime("%m/%d/%Y") : 'Not Set'

app/views/tasks/edit.haml
= render "form", task: @task

app/views/tasks/index.haml
%p{style: "color: green"}
  = notice

#tasks-container
  #tasks
    - @tasks.each do |task|
      = render task
  = render 'new'
  .modal
    .modal-dialog
      .modal-content
        Bootstrap button